/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright(C) 2026 Spacemit Limited. All rights reserved.
 * Author: liangzhen <zhen.liang@spacemit.com>
 */

#ifndef _RVTRACE_ENCODER_H
#define _RVTRACE_ENCODER_H

#include <asm/local.h>
#include <linux/spinlock.h>
#include "coresight-priv.h"
#include "rvtrace-timestamp.h"

/* Trace Encoder Control Register */
#define RVTRACE_ENCODER_ITRACE				    BIT(2)
#define RVTRACE_ENCODER_INSTMODE			    GENMASK(6, 4)
#define RVTRACE_ENCODER_CONTEXT			   	    BIT(9)
#define RVTRACE_ENCODER_INSTTRIGEN			    BIT(11)
#define RVTRACE_ENCODER_INST_STALL_OR_OVERFLOW   	    BIT(12)
#define RVTRACE_ENCODER_INST_STALL_EN			    BIT(13)
#define RVTRACE_ENCODER_INHBSRC				    BIT(15)
#define RVTRACE_ENCODER_INSTSYNC_MODE			    GENMASK(17, 16)
#define RVTRACE_ENCODER_INSTSYNC_MAX			    GENMASK(23, 20)

#define RVTRACE_COMPONENT_CTRL_ITRACE_SHIFT		    2

/* Trace Encoder Implementation Register */

/* Trace Instruction Features Register */
#define RVTRACE_ENCODER_INST_FTRS_OFFSET		    0x008
#define RVTRACE_ENCODER_INST_NO_ADDR_DIFF		    BIT(0)
#define RVTRACE_ENCODER_INST_NO_TRAP_ADDR		    BIT(1)
#define RVTRACE_ENCODER_INST_EN_SEQUENTIAL_JUMP		    BIT(2)
#define RVTRACE_ENCODER_INST_EN_IMPLICIT_RETURN		    BIT(3)
#define RVTRACE_ENCODER_INST_EN_BRANCH_PREDICTION	    BIT(4)
#define RVTRACE_ENCODER_INST_JUMP_TARGET_CACHE		    BIT(5)
#define RVTRACE_ENCODER_INST_IMPLICIT_RETURN_MODE	    GENMASK(7, 6)
#define RVTRACE_ENCODER_INST_EN_REPEQTED_HISTORT	    BIT(8)
#define RVTRACE_ENCODER_INST_EN_ALL_JUMPS		    BIT(9)
#define RVTRACE_ENCODER_INST_EXTEND_ADDR_MSB		    BIT(10)
#define RVTRACE_ENCODER_SRCID				    GENMASK(27, 16)
#define RVTRACE_ENCODER_SRCBITS				    GENMASK(31, 28)

enum encoder_format {
	ENCODER_FORMAT_ETRACE,
	ENCODER_FORMAT_NTRACE,
	ENCODER_FORMAT_UNKNOWN = 7
};

enum encoder_instmode {
	ENCODER_INSTMODE_OFF,
	ENCODER_INSTMODE_RESV1,
	ENCODER_INSTMODE_RESV2,
	ENCODER_INSTMODE_BTM,
	ENCODER_INSTMODE_RESV4,
	ENCODER_INSTMODE_RESV5,
	ENCODER_INSTMODE_HTM,
	ENCODER_INSTMODE_RESV7
};

enum encoder_syncmode {
        ENCODER_SYNCMODE_OFF,
        ENCODER_SYNCMODE_MESSAGES,
        ENCODER_SYNCMODE_CLOCK,
        ENCODER_SYNCMODE_INSTRUCTION
};

enum encoder_implicit_return_mode {
        ENCODER_IMPLICITRETURNMODE_NOT_SUPPORTED,
        ENCODER_IMPLICITRETURNMODE_SIMPLE_COUNTING,
        ENCODER_IMPLICITRETURNMODE_PARTIAL_ADDRESS,
        ENCODER_IMPLICITRETURNMODE_FULL_ADDRESS
};

/**
 * struct encoder_config - configuration information related to an trace encoder
 * @context:		Controls sending trace messages/fields with scontext/mcontext
 *			values and/or privilege levels.
 * @inst_trig:		Controls trTeInstTracing to be set or cleared by Trace-on and
 *			Trace-off signals generated by the corresponding trigger module.
 * @inst_stall:		Controls whether hart is stalled until TE can send a message.
 * @inhb_src:		Controls whether include source field in trace messages/packets.
 * @inst_syncmode:	Periodic instruction trace synchronization message/packet
 *			generation mechanism.
 * @inst_syncmax:	The maximum interval between instruction trace synchronization
 *			messages/packets.
 * @trc_fmt:		Trace recording/protocol format.
 * @inst_na_diff:	Controls whether trace messages/packets always carry a full address.
 * @inst_nt_addr:	Controls whether include trap handler address in trap messages/packets.
 * @seq_jump:		Controls the sequential jump optimization.
 * @impl_ret:		Controls the implicit return optimization.
 * @branch_pred:	Branch Predictor based compression.
 * @jump_target_cache:	Jump Target Cache based compression.
 * @impl_ret_mode:	Controls how the decoder is handling stack of return addresses.
 * @rep_hist:		Controls the repeated history optimization.
 * @all_jumps:		Controls the emitting of trace message or add history/map bit for
 *			direct unconditional/inferable control flow changes.
 * @ext_msb:		Controls the extended handing of MSB address bits.
 * @srcid:		Trace source ID assigned to this trace encoder.
 * @srcb:		The number of bits in the trace source field, unless disabled by
 *			inhibit_src.
 */
struct encoder_config {
	bool				    context;
	bool				    inst_trigger;
	bool				    inst_stall;
	bool				    inhb_src;
	u8				    inst_syncmode;
	u8				    inst_syncmax;
	bool				    inst_na_diff;
	bool				    inst_nt_addr;
	bool				    seq_jump;
	bool				    impl_ret;
	bool				    branch_pred;
	bool				    jump_target_cache;
	u8				    impl_ret_mode;
	bool				    rep_hist;
	bool				    all_jumps;
	bool				    ext_msb;
	u16				    srcid;
	u8				    srcb;
};

/**
 * struct encoder_save_state - state to be preserved when encoder is without power
 */
struct encoder_save_state {
	u32	control;
	u32	features;
	u32	ts_control;
};

/**
 * struct encoder_drvdata - specifics associated to an Trace Encoder component
 * @csdev:	    Component vitals needed by the framework.
 * @spinlock:	    Only one at a time pls.
 * @sticky_enable:  True if trace encoder base configuration has been done.
 * @boot_enable:    True if we should start tracing at boot time.
 * @has_timestamp:  True if this encoder has timestamp component.
 * @ts_ctrl:        Controls the insertion of global timestamps in the trace streams.
 * @config:	    Structure holding configuration parameters.
 * @ts_config:	    Timestamp configuration.
 */

struct encoder_data {
	struct coresight_device		    *csdev;
	spinlock_t                          spinlock;
	bool                                sticky_enable;
	bool                                boot_enable;
	bool                                has_timestamp;
	bool                                ts_ctrl;
	struct encoder_config		    config;
	struct timestamp_config		    ts_config;
	struct encoder_save_state	    *save_state;
};

extern const struct attribute_group *trace_encoder_groups[];
void encoder_set_default(struct rvtrace_component *comp);

#endif
