#!/bin/bash -e
# ---------------------------------------------------------------------------
# make_signed_kernel_deb.sh
#
# Post-process the complete linux-image deb generated by bindeb-pkg:
#   1. generate a signed FIT from a generated or customer ITS;
#   2. unpack the existing canonical linux-image deb;
#   3. inject /boot/Image.itb, update metadata and postinst;
#   4. rebuild the same deb filename atomically.
#
# Inputs (environment):
#   KEY_DIR       required directory containing <hint>.key and <hint>.crt
#   KEY_HINT      key-name-hint (default: kernel_key_prv)
#   MKIMAGE       mkimage path (default: PATH)
#   KERNEL_ITS    optional customer ITS; generated when unset
#   KERNEL_IMAGE  directory containing Image and/or Image.gz
#                 (default: arch/riscv/boot)
#   DTB_DIR       directory containing board DTBs
#                 (default: arch/riscv/boot/dts/spacemit)
#   DTB_LIST      space-separated DTB basenames for generated ITS
#   KDEB_PKGVERSION / KERNELRELEASE
#   DEB_IN        optional canonical linux-image deb to transform
# ---------------------------------------------------------------------------

KDIR="$(cd "$(dirname "$0")/.." && pwd)"
KEY_HINT="${KEY_HINT:-kernel_key_prv}"
KERNEL_IMAGE="${KERNEL_IMAGE:-$KDIR/arch/riscv/boot}"
DTB_DIR="${DTB_DIR:-$KDIR/arch/riscv/boot/dts/spacemit}"
OUT_DIR="${OUT_DIR:-$(cd "$KDIR/.." && pwd)}"

if [ -z "${MKIMAGE:-}" ]; then
    if command -v mkimage >/dev/null 2>&1; then
        MKIMAGE="$(command -v mkimage)"
    else
        echo "[signed-deb][ERROR] mkimage not found (set MKIMAGE=)" >&2
        exit 1
    fi
fi

PKGVER="${KDEB_PKGVERSION:-${KERNELRELEASE:-unknown}}"
if [ -f "$KDIR/include/config/kernel.release" ]; then
    ABI="$(cat "$KDIR/include/config/kernel.release")"
else
    ABI="${KERNELRELEASE:-unknown}${LOCALVERSION:-}"
fi
DEB_IN="${DEB_IN:-$OUT_DIR/linux-image-${ABI}_${PKGVER}_riscv64.deb}"

case "$KERNEL_IMAGE" in
    /*) KIMAGE_DIR="$KERNEL_IMAGE" ;;
    *) KIMAGE_DIR="$KDIR/$KERNEL_IMAGE" ;;
esac
case "$DTB_DIR" in
    /*) DTB_DIR_ABS="$DTB_DIR" ;;
    *) DTB_DIR_ABS="$KDIR/$DTB_DIR" ;;
esac

echo "=========================================================="
echo "[signed-deb] post-processing canonical linux-image deb"
echo "[signed-deb] input deb = $DEB_IN"
echo "[signed-deb] key dir   = ${KEY_DIR:-<unset>}"
echo "[signed-deb] key hint  = $KEY_HINT"
echo "[signed-deb] its       = ${KERNEL_ITS:-<generated>}"
echo "[signed-deb] image dir = $KIMAGE_DIR"
echo "[signed-deb] dtb dir   = $DTB_DIR_ABS"
echo "[signed-deb] abi       = $ABI"
echo "=========================================================="

[ -n "${KEY_DIR:-}" ] || { echo "[signed-deb][ERROR] KEY_DIR not set" >&2; exit 1; }
[ -d "$KEY_DIR" ] || { echo "[signed-deb][ERROR] KEY_DIR not a dir: $KEY_DIR" >&2; exit 1; }
[ -f "$KEY_DIR/$KEY_HINT.key" ] || { echo "[signed-deb][ERROR] missing $KEY_DIR/$KEY_HINT.key" >&2; exit 1; }
[ -f "$KEY_DIR/$KEY_HINT.crt" ] || { echo "[signed-deb][ERROR] missing $KEY_DIR/$KEY_HINT.crt" >&2; exit 1; }
[ -x "$MKIMAGE" ] || { echo "[signed-deb][ERROR] mkimage not executable: $MKIMAGE" >&2; exit 1; }
[ -d "$KIMAGE_DIR" ] || { echo "[signed-deb][ERROR] KERNEL_IMAGE directory not found: $KIMAGE_DIR" >&2; exit 1; }
[ -d "$DTB_DIR_ABS" ] || { echo "[signed-deb][ERROR] DTB_DIR not found: $DTB_DIR_ABS" >&2; exit 1; }
[ -f "$DEB_IN" ] || { echo "[signed-deb][ERROR] canonical linux-image deb not found: $DEB_IN" >&2; exit 1; }

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
mkdir -p "$WORK/kernel"
ITS="$WORK/kernel_fdt_sign.its"

# Generate a simple, documented default ITS. Input staging is deliberately
# deferred to the common incbin parser below, shared with custom ITS files.
if [ -n "${KERNEL_ITS:-}" ]; then
    [ -f "$KERNEL_ITS" ] || { echo "[signed-deb][ERROR] KERNEL_ITS not found: $KERNEL_ITS" >&2; exit 1; }
    cp "$KERNEL_ITS" "$ITS"
    echo "[signed-deb] using customer ITS: $KERNEL_ITS"
else
    if [ -n "${DTB_LIST:-}" ]; then
        DTBS="$DTB_LIST"
    else
        DTBS="$(cd "$DTB_DIR_ABS" && ls *.dtb 2>/dev/null || true)"
    fi
    [ -n "$DTBS" ] || { echo "[signed-deb][ERROR] no DTB found in $DTB_DIR_ABS" >&2; exit 1; }

    {
        echo '/dts-v1/;'
        echo '/ {'
        echo '	description = "Signed image with single Linux kernel and FDT blob";'
        echo '	#address-cells = <2>;'
        echo '	images {'
        echo '		kernel {'
        echo '			description = "Spacemit Linux kernel";'
        echo '			data = /incbin/("./Image.gz");'
        echo '			type = "kernel";'
        echo '			arch = "riscv";'
        echo '			os = "linux";'
        echo '			compression = "gzip";'
        echo '			load = <0x1 0x02000000>;'
        echo '			entry = <0x1 0x02000000>;'
        echo '			hash { algo = "sha256"; };'
        echo '		};'
        idx=0
        for dtb in $DTBS; do
            [ -f "$DTB_DIR_ABS/$dtb" ] || { echo "[signed-deb][ERROR] missing DTB: $DTB_DIR_ABS/$dtb" >&2; exit 1; }
            idx=$((idx + 1))
            printf '\t\tfdt_%s {\n' "$idx"
            printf '\t\t\tdescription = "Flattened Device Tree blob for %s";\n' "$dtb"
            printf '\t\t\tdata = /incbin/("./kernel/%s");\n' "$dtb"
            echo '			type = "flat_dt";'
            echo '			arch = "riscv";'
            echo '			compression = "none";'
            echo '			load = <0x1 0x28000000>;'
            echo '			hash { algo = "sha256"; };'
            echo '		};'
        done
        echo '	};'
        echo '	configurations {'
        echo '		default = "conf_1";'
        idx=0
        for dtb in $DTBS; do
            idx=$((idx + 1))
            board="${dtb%.dtb}"
            printf '\t\tconf_%s {\n' "$idx"
            printf '\t\t\tdescription = "%s";\n' "$board"
            echo '			kernel = "kernel";'
            printf '\t\t\tfdt = "fdt_%s";\n' "$idx"
            echo '			signature {'
            echo '				algo = "sha256,rsa2048";'
            printf '\t\t\t\tkey-name-hint = "%s";\n' "$KEY_HINT"
            echo '				sign-images = "kernel", "fdt";'
            echo '			};'
            echo '		};'
        done
        echo '	};'
        echo '};'
    } > "$ITS"
    echo "[signed-deb] generated ITS with $idx config(s): $DTBS"
fi

# Stage every ITS incbin input. Generated and customer ITS files use the exact
# same path; only Image, Image.gz and kernel/<relative-dtb> are supported.
incbin_total="$(grep -c 'incbin' "$ITS" || true)"
incbin_parsed=0
while IFS= read -r incbin; do
    incbin_parsed=$((incbin_parsed + 1))
    case "$incbin" in
        ./Image.gz)
            [ -f "$KIMAGE_DIR/Image.gz" ] || { echo "[signed-deb][ERROR] missing $KIMAGE_DIR/Image.gz for $incbin" >&2; exit 1; }
            cp "$KIMAGE_DIR/Image.gz" "$WORK/Image.gz"
            ;;
        ./Image)
            [ -f "$KIMAGE_DIR/Image" ] || { echo "[signed-deb][ERROR] missing $KIMAGE_DIR/Image for $incbin" >&2; exit 1; }
            cp "$KIMAGE_DIR/Image" "$WORK/Image"
            ;;
        ./kernel/*)
            dtb="${incbin#./kernel/}"
            case "$dtb" in
                ""|/*|../*|*/../*|*/..)
                    echo "[signed-deb][ERROR] unsafe DTB incbin path: $incbin" >&2
                    exit 1
                    ;;
            esac
            [ -f "$DTB_DIR_ABS/$dtb" ] || { echo "[signed-deb][ERROR] missing $DTB_DIR_ABS/$dtb for $incbin" >&2; exit 1; }
            mkdir -p "$WORK/kernel/$(dirname "$dtb")"
            cp "$DTB_DIR_ABS/$dtb" "$WORK/kernel/$dtb"
            ;;
        *)
            echo "[signed-deb][ERROR] unsupported incbin path: $incbin" >&2
            exit 1
            ;;
    esac
done < <(grep "incbin" "$ITS" | sed -n 's@.*incbin/[[:space:]]*([[:space:]]*"\([^"]*\)"[[:space:]]*).*@\1@p')
[ "$incbin_total" -eq "$incbin_parsed" ] || { echo "[signed-deb][ERROR] failed to parse all incbin entries: total=$incbin_total parsed=$incbin_parsed" >&2; exit 1; }
[ "$incbin_parsed" -gt 0 ] || { echo "[signed-deb][ERROR] ITS contains no incbin input" >&2; exit 1; }
echo "[signed-deb] staged $incbin_parsed ITS input(s)"

( cd "$WORK" && "$MKIMAGE" -f kernel_fdt_sign.its -k "$KEY_DIR" -r Image.itb )
echo "[signed-deb] signed Image.itb ready"

# Unpack the complete bindeb-pkg output, preserving modules, vmlinuz, DTBs,
# generated maintainer scripts and all original metadata.
PKGDIR="$WORK/pkg"
dpkg-deb -R "$DEB_IN" "$PKGDIR"
[ -d "$PKGDIR/boot" ] || { echo "[signed-deb][ERROR] deb lacks boot directory" >&2; exit 1; }
[ -f "$PKGDIR/DEBIAN/control" ] || { echo "[signed-deb][ERROR] deb lacks DEBIAN/control" >&2; exit 1; }
[ -f "$PKGDIR/DEBIAN/postinst" ] || { echo "[signed-deb][ERROR] deb lacks DEBIAN/postinst" >&2; exit 1; }

cp "$WORK/Image.itb" "$PKGDIR/boot/Image.itb"

# Secure boot uses Image.itb exclusively; vmlinuz is never loaded by U-Boot.
printf 'STUB' > "$PKGDIR/boot/vmlinuz-$ABI"

# The new postinst operation requires linux-update-symlinks from linux-base.
CONTROL="$PKGDIR/DEBIAN/control"
if ! grep -Eq '^Depends:.*(^|, )linux-base(,|$)' "$CONTROL"; then
    sed -i '/^Depends:/ s/$/, linux-base/' "$CONTROL"
fi
if grep -q '^Provides:' "$CONTROL"; then
    if ! grep -Eq '^Provides:.*(^|, )spacemit-signed-kernel-image(,|$)' "$CONTROL"; then
        sed -i '/^Provides:/ s/$/, spacemit-signed-kernel-image/' "$CONTROL"
    fi
else
    printf 'Provides: spacemit-signed-kernel-image\n' >> "$CONTROL"
fi
for field in Conflicts Replaces; do
    if grep -q "^$field:" "$CONTROL"; then
        if ! grep -Eq "^$field:.*(^|, )spacemit-signed-kernel-image(,|$)" "$CONTROL"; then
            sed -i "/^$field:/ s/$/, spacemit-signed-kernel-image/" "$CONTROL"
        fi
    else
        printf '%s: spacemit-signed-kernel-image\n' "$field" >> "$CONTROL"
    fi
done

# Original postinst first runs initramfs/kernel hooks. Append the explicit
# symlink update after those hooks, preserving the generated script content.
POSTINST="$PKGDIR/DEBIAN/postinst"
sed -i '/^exit 0$/d' "$POSTINST"
cat >> "$POSTINST" <<POSTINST_EOF

ABI="$ABI"
command -v linux-update-symlinks >/dev/null 2>&1 || {
    echo "signed-fit: linux-update-symlinks missing (linux-base dependency broken)" >&2
    exit 1
}
[ -e "/boot/vmlinuz-$ABI" ] || {
    echo "signed-fit: /boot/vmlinuz-$ABI missing" >&2
    exit 1
}
linux-update-symlinks install "$ABI" "/boot/vmlinuz-$ABI"
exit 0
POSTINST_EOF
chmod 0755 "$POSTINST"

# Preserve the original package md5 list and add the injected FIT entry.
MD5SUMS="$PKGDIR/DEBIAN/md5sums"
[ -f "$MD5SUMS" ] || { echo "[signed-deb][ERROR] deb lacks DEBIAN/md5sums" >&2; exit 1; }
sed -i '\|  boot/Image.itb$|d' "$MD5SUMS"
sed -i '\|  boot/vmlinuz-'"$ABI"'$|d' "$MD5SUMS"
( cd "$PKGDIR" && md5sum boot/Image.itb boot/vmlinuz-"$ABI" ) >> "$MD5SUMS"

# Atomically replace the original complete deb with its signed equivalent.
DEB_TMP="$DEB_IN.tmp"
rm -f "$DEB_TMP"
dpkg-deb --root-owner-group --build "$PKGDIR" "$DEB_TMP"
mv -f "$DEB_TMP" "$DEB_IN"

echo "[signed-deb] rebuilt $DEB_IN"
echo "[signed-deb] ===== mkimage -l Image.itb ====="
"$MKIMAGE" -l "$WORK/Image.itb" || true
echo "=========================================================="
